name: Build AAR

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build AAR
        run: ./gradlew assembleRelease

      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: BoxedVerticalSeekBar-aar
          path: app/build/outputs/aar/*.aar
