name: Build AAR

on:
  workflow_dispatch:   # bisa dijalankan manual dari tab Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      # 🔹 Build hanya modul library, skip app
      - name: Build library AAR
        run: ./gradlew :BoxedVerticalSeekBarLib:assembleRelease

      # 🔹 Upload hasil build agar bisa di-download dari tab Actions
      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: BoxedVerticalSeekBar-aar
          path: BoxedVerticalSeekBarLib/build/outputs/aar/*.aar
